package com.exampleSenpiper.senPiper.model;


import org.json.JSONPropertyName;
import org.springframework.stereotype.Component;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
@Component
@Entity
@Table(name = "centerTraining")
public class Center {

//    Student Capacity (number)
//○ Courses Offered (List<text>)
//○ CreatedOn (Epoch time generated by System, not by user)
//○ ContactEmail (text) (If present, email should be validated)
//            ○ ContactPhone (text)* (Phone number validation




    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotEmpty
    @Size(max = 40)
    private String centerName;
    @NotEmpty
    @Size(max = 12, min = 12)
    private String centerCode;

    @NotNull
    @OneToOne(cascade = CascadeType.ALL)
    private Address address;
    private int studentCapacity;

    @Column
    @Convert(converter = ListToStringConverter.class)
    private List<String> coursesOffered;

    @Column(unique = true)
    private String email;
    @Column(unique = true)
    @NotEmpty
    private String phoneNo;


    private String createdOn;

    public void setCreatedOn(String createdOn) {
        this.createdOn = createdOn;
    }

    public String getCreatedOn() {
        return createdOn;
    }

    public String getCenterName() {
        return centerName;
    }

    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }

    public String getCenterCode() {
        return centerCode;
    }

    public void setCenterCode(String centerCode) {
        this.centerCode = centerCode;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public int getStudentCapacity() {
        return studentCapacity;
    }

    public void setStudentCapacity(int studentCapacity) {
        this.studentCapacity = studentCapacity;
    }

    public List<String> getCoursesOffered() {
        return coursesOffered;
    }

    public void setCoursesOffered(List<String> coursesOffered) {
        this.coursesOffered = coursesOffered;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
}
